module.exports = {
  config: {
    fontSize: 14,
    fontFamily: 'Operator Mono Lig, Operator Mono, Dank Mono',
    cursorColor: 'cyan',
    cursorShape: 'BLOCK',
    foregroundColor: '#fff',
    backgroundColor: '#000',
    borderColor: '#333',
    css: '',
    termCSS: '',
    showHamburgerMenu: '',
    showWindowControls: 'false',
    padding: '12px 12px',
   shell: 'zsh',
    shellArgs: ['--login'],
    env: {},
    bell: 'false',
    copyOnSelect: false,
    windowSize: [1920, 1080]
  },
  plugins: ['hyperfullscreen', 'hyperfull', // 'hyper-line',
  // 'hyperterm-tabs',
  // 'hyper-alt-click',
  // 'hyper-tab-icons',
  // 'hyper-spotify',
  // 'gitrocket'
  'hypercwd', "hyper-night-owl"],
  localPlugins: [],
};
