module.exports = {
  config: {
    fontSize: 14,
    fontFamily: 'Operator Mono Lig, Operator Mono, Dank Mono',
    cursorColor: 'cyan',
    cursorShape: 'BLOCK',
    foregroundColor: '#fff',
    backgroundColor: '#000',
    borderColor: '#333',
    css: '',
    termCSS: '',
    showHamburgerMenu: '',
    showWindowControls: 'false',
    padding: '12px 12px',
    colors: {
      black: '#000000',
      red: '#ff0000',
      green: '#33ff00',
      yellow: '#ffff00',
      blue: '#0066ff',
      magenta: '#cc00ff',
      cyan: '#00ffff',
      white: '#d0d0d0',
      lightBlack: '#808080',
      lightRed: '#ff0000',
      lightGreen: '#33ff00',
      lightYellow: '#ffff00',
      lightBlue: '#0066ff',
      lightMagenta: '#cc00ff',
      lightCyan: '#00ffff',
      lightWhite: '#ffffff'
    },
    shell: 'zsh',
    shellArgs: ['--login'],
    env: {},
    bell: 'false',
    copyOnSelect: false,
    windowSize: [1920, 1080]
  },
  plugins: ['hyperfullscreen', 'hyperfull', // 'hyper-line',
  // 'hyperterm-tabs',
  // 'hyper-alt-click',
  // 'hyper-tab-icons',
  // 'hyper-spotify',
  // 'gitrocket'
  'hypercwd', "hyper-night-owl"],
  localPlugins: [],
};
